### ISSUE TITLE
Private/public message  Edit messages

### ISSUE THREAD

**Issue by ajohnsson95** [Ebyrdeu/spring_boot_library#19]
1. Should we not have an option for Private/Public messages

2. Who is supposed to Edit messages, Titles etc... Is it just the User that created the message or do we want Admin to have the option aswell

**Comment by Ebyrdeu** [comment]
I didn't watch this week's Martins lectures, so I'm not sure if he covered OAuth2 server. I only tested Spring Security, and it's a lot of work just for simple authentication and authorization with jwt. But for now, I want to finish just with simple CRUD without any admin/user/guest permission, essentially no security at all, and only then start to add it. But know about you guys, what do you think ?

**Comment by ValentinaSukonina** [comment]
Idea of implementing Private/Public sounds very reasonable. OAuth2 itself does not inherently enforce public or private access to data upon login. There are however should be possibility to grant public access to certain resources or data upon successful authentication and authorization. Do not know how easy is that to implement. It can be an easier solution.
