### ISSUE TITLE
[FEATURE] - Profile image functionality

### ISSUE THREAD

**Issue by Charlottehenriksson** [Ebyrdeu/spring_boot_library#29]
### Problem Description
We need to implement image functionality to the profile user.

**Comment by Ebyrdeu** [comment]
Principal that you get from github oauth2 returns a url for image.
in html you just use `<img/>` tag 
[my avatar](https://avatars.githubusercontent.com/u/42122071?v=4) from this principal 

![image](https://github.com/Ebyrdeu/spring_boot_library/assets/42122071/b16b4d31-a519-4beb-9560-cb247290a247)
