### ISSUE TITLE
[FEATURE] - Auditing to save user session data

### ISSUE THREAD

**Issue by Charlottehenriksson** [Ebyrdeu/spring_boot_library#31]
### Problem Description
Vi behöver lagra användare lokalt i en User
tabell och vilka roller de har men själva authentication delen sköter Github.
https://docs.spring.io/spring-session/reference/guides/boot-redis.html

**Comment by Ebyrdeu** [comment]
mmmm, I feel similarly about Flyway; it seems a bit overkill for our project. But if you or someone else wants to implement it, sure, why not I guess

**Comment by ajohnsson95** [comment]
Could use a function called Auditing that is a application Spring data JPA offers to save session data

**Comment by ValentinaSukonina** [comment]
Branch is merged to main
