### ISSUE TITLE
Add libretranslate docker and cache implementation

### ISSUE THREAD

**Issue by ValentinaSukonina** [Ebyrdeu/spring_boot_library#35]
We need to integrate LibreTranslate Docker to utilize its translation services. Additionally, we need to decide on caching options for LibreTranslate, where it's beneficial to track the original language of messages and their translations. Should we implement Redis for this purpose, or utilize a simple in-memory cache managed by, for instance, SimpleCacheManager? While LibreTranslate has internal Redis for caching often translated phrases, accessing it directly from our application may not be advisable.

**Comment by Charlottehenriksson** [comment]
This is what i found: 
If your application serves a small user base or has relatively low translation traffic, a simple in-memory cache may suffice.
However, as your application scales and translation requests increase, you may encounter performance bottlenecks with an in-memory cache.

Perhaps redis is not needed if we need to make it simple for us with the due date soon? :)
