### ISSUE TITLE
Add pagination for Messages and Users

### ISSUE THREAD

**Issue by ValentinaSukonina** [Ebyrdeu/spring_boot_library#46]
Adding pagination to a web page allows users to load only partial content of the web site, resulting in faster initial page loads and better overall performance.

**Comment by ValentinaSukonina** [comment]
Pagination was mentioned in the project requirement. Do you think we need it for both Messages and Users, or only for Messages?

**Comment by Ebyrdeu** [comment]
Only for Messages, unless you want to do same with Users. Like for example as admin you can delete any users from database.

**Comment by ValentinaSukonina** [comment]
> Only for Messages, unless you want to do same with Users. Like for example as admin you can delete any users from database.

I also thought the Messages are more important. I'll try to push those implementations today
